Just enrolled in SQL for Data Science EDX Course
================================================

***I HAVE TO UPGRADE TO VERIFIED COURSE BEFORE FEB 11TH!!!***

I want to take notes here and keep track of my progress.

If I'm doing well and think it's worth it, I will upgrade before Feb 11.

GRADING SCHEME

This section contains information for those earning a certificate. Those auditing the course can skip this section and click next.

1. The course contains 5 Graded Quizzes (1 per module) worth 75% of the total grade. Each Graded Quiz carries an equal weight of 15% of the total grade.
2. The course also includes a Final Assignment worth 25% of the total grade.
3. The minimum passing mark for the course is 70%.
4. Permitted attempts are per question:
 
1 attempt for true/false Qs
2 attempts for all others

Final assignment - *Only 1 attempt for all questions!!*

Module 1
--------

Learning Objectives

- Explain SQL and Relational Databases
- Create a database instance on the Cloud

Welcome Video:

Data Science median salary: $110,000pa
  - not bad

SQL a language used for querying data in a relational database

SQL and databases are absolutely everywhere.

I hope the whole course isn't just a bunch of videos. If I wanted to watch videos I'd just use YouTube right?

---

### How to create a Database Instance on a Cloud ###

- You need a database before you can practise SQL

- We're going to create an instance of this on a cloud

This lesson:

- basic database concepts
- list a few cloud databases
- describe database instances
- demonstrate how to create an instance

#### Databases ####

A cloud database is a database service built and accessed through a cloud platform

It works like any traditional database, but with the flexibility of cloud platforms

Advantages of cloud computing:

- Ease of use
  - clouds are accessible from anywhere using a vendors API or web interface
- Scalability
  - cloud databases can expand or shrink their capabilities depending on client needs
- Disaster recovery
  - multiple backups of data are kept secure across remote servers worldwide

Cloud Databases:

- IBM Db2 on Cloud,
- PostgreSQL on IBM Cloud, 
- Oracle Database Cloud Service,
- Microsoft Azure SQL Database, and
- Amazon Relational Database Services. 

These cloud databases can run in the cloud either as a virtual machine.

They can be single or multi-tenant depending on the plan.

Running a database:

- provision an instance of a database

This gives you access to the database cloud resources without having to set up the underlying hardware.

Basically you can have a databse without need to buy all the gear yourself and get it all set up and maintaining it (could put people like David out of a job!)

The db service will hold your relational tables.

Once your data has been stored you can connect, and can then interface using SQL queries.

Your SQL statements are sent to the database instance, the instance then "resolves the SQL statements into operations against the data and objects in the database. Any data
retrieved is returned to the application as a result set" - i.e. you will send a query, and it will return a result to your browser/API whatever.

Wow, well that was just a huge stuff around. Very poorly explained video, took me ages to get to where I needed to get to.

This course is going to take a really long time at this rate.

So I just navigated to the IBM cloud site, created an account, and spent quite some time getting to the same point as the video. It was very poorly explained, and the video is a series of screen shots, which makes it difficult.

I hope the whole course isn't like this.

Now I can't even remember how I did it. But after stuffing around for a while, I somehow eventually ended up on the page that the tutorial appeared to be on, and eventually got to the console section it directed me too, but oops, I have to create service credentials, which are in a different section (don't get confused!).

I eventually created my service credentials:

I feel like I should save this somewhere else, and not save it to GitHub. Seems important.

Done.

---

### Relational Datbase Concepts ###

This video:

- advantage of relational model
- describe how an entity name and atributes map to a table
- difference between an entity and an attribute
- identify common data types
- describe the function of primary keys

#### Relational database ####

- the most used data model
- allows for data independence
- data is stored in tables

Entity relationship data model is an alternative to a relational data model

Entity model is used to design the relational database?

Entities are nouns: person, place, thing

- drawn as rectangles
- entities contain attributes (ovals) which provide information about the entity
- attributes are connected to exactly one entity
- the entity becomes a table in the database (makes sense)
- columns becomes the attributes

Entity:
attribute attribute attribute attribute 

for columns which vary in length: varchar
for columns which dont vary: char

Primary key uniquely identifies each row (tuple!), preventing duplication

Foreign keys - primary keys defined in other tables - allow linking of information

I pretty much know all this already, but it's nice to be refreshed on the specific details.

There's also a few different conventions, it would be good to try to memorise important stuff like 'varchar' and 'char', and other data types.

OK, so the next step is a step by step guide to creating an IBM db2 account and instance, which I've already struggled through.

To their credit, it appears that the practical is a much clearer guide through the process.

NOTE: - I should just watch all the videos and try to take notes, and see if practicals clear things up a bit at the end!
  - This should save me some time

So I can't actually take the assessemnts unless I upgrade!!
  - Which means I either upgrade now, or I come back later and do the assessments - after I've probably forgotten everything already!
  - Gah!

Think about this today and decide tomorrow.

- Do another 1 - 2 modules (then you'll be halfway through geez)
  - Keep taking notes
  - If you're confident the course will get you what you want, then go for it
  - Otherwise you need to find a way to showcase your skills
    - Use them to build your database
    - Keep track of the code you use and push it to GitHub

---

Module 2
--------

Learning objectives

- How to write basic SQL statements
- Practise them in a live database (save these and push to GitHub)

### Create a Table ###

Database objects:

Entities = tables
Attributes = columns
Tuples = Rows

#### Data definition language statements ####

DDL are used to define, change or drop database objects

CREATE - creating data tables, defining columns
ALTER - altering tables - adding dropping columns, modifying data types
TRUNCATE - deleting data in a table, but not the table itself
DROP - deleting tables

Are all data

#### Data manipulation language statements ####

Read and modify data in tables

- CRUD - create, read, update, delete

INSERT - inserting data
SELECT - reads or selects data
UPDATE - updates data in a table
DELETE - deletes data from a table

```{sql}
CREATE TABLE table_name
  (
  column_name_1 datatype optional_parameters,
  column_name_2 datatype,
  ...
  column_name_n datatype
  )
```

```{sql}
CREATE TABLE author
(
author_id CHAR(2) PRIMARY KEY NOT NULL,
lastname VARCHAR(15) NOT NULL,
firstname VARCHAR(15) NOT NULL,
email VARCHAR(4) NOT NULL,
city VARCHAR(15),
country CHAR(2)
)
```

[//]: # ( This all feels terribly redundant. I learned all this exactly a year ago, and I learned it faster than this )
[//]: # ( It's OK, just keep going quickly through - see how it goes, it may get better/more technical later on - You'll still be able to get the certificate )
[//]: # ( I'm sure if I just kept working on my Music data base, I'd continue to pick up concepts faster than this )
[//]: # ( I just need to do a good job of ensuring that I have these requesite skills, and can demonstrate them to employers )

### SELECT statement ###

select is a DML (data manipulation language) statement

- read and modify data

select * from 'tablename'

e.g.:

```{sql}
SELECT book_id, title FROM book
```

To add a condition (i.e. a specific type of book), use WHERE

```{sql}
SELECT book_id, title FROM book WHERE book_id='B1'
```

[//]: # ( Just changed to a Rmd doc, so now blocks have syntax highlighting. Much better )

Ah... I think I see now, the blue ones are DDL statements and the green ones are DML statements. Well I guess this course is teaching me something afterall.

---

count() allows you to select a specific number of rows

```{sql}
SELECT COUNT(*) FROM tablename

```

for example:

```{sql}
SELECT COUNT(COUNTRY) FROM medals WHERE country='CANADA'
```

distinct is used to remove duplicate values

```{sql}
SELECT DISTINCT COUNTRY FROM medals WHERE medaltype='gold'
```

limit - for restricting the number of rows retrieved

```{sql}
SELECT * FROM medals LIMIT 10
```

```{sql}
SELECT * FROM medals WHERE YEAR = 2018 LIMIT 10
```

### INSERT statement ###

DML statement

Used to insert data into a table (duh!)

```{sql}
INSERT INTO AUTHOR
(AUTHOR_ID, LASTNAME, FIRSTNAME, EMAIL, CITY, COUNTRY)
VALUES 
('A1', 'Chong', 'Raul', 'rfc@ibm.com', 'Toronto', 'CA')
```

Multiple rows can be inserted at once.

```{sql}
INSERT INTO AUTHOR
(AUTHOR_ID, LASTNAME, FIRSTNAME, EMAIL, CITY, COUNTRY)
VALUES 
('A1', 'Chong', 'Raul', 'rfc@ibm.com', 'Toronto', 'CA')
('A1', 'Ajhuv', 'Tim', 'AT@ibm.com', 'Toronto', 'CA')
('A1', 'Johnson', 'Paul', 'PJ@ibm.com', 'Toronto', 'CA')
('A1', 'Chong', 'Rick', 'RC@ibm.com', 'Miami', 'FL')
```

### UPDATE and DELETE statements ###

Used to modify data in a table

Syntax of update statement:

    UPDATE [TableName] SET [[ColumnName]=[Value]] 

Syntax of delete statement:

    DELETE FROM [tablename] WHERE [condition]

So there are '5 basic SQL statements'. Seems simple enough.

Module 3
--------

### Using sting patterns and ranges ###

Using the `SELECT` statement

Apparently these are 'advanced' techniques. Does that mean I can call myself an 'intermediate' user after I've learnt them?

Lesson: simplifying select staements by using tring patterns, ranges or sets of values.

The simplest select stateemnt is:

```{sql}
SELECT * FROM table_name
```

This will retrieve an entire table, and all of its contents

What if we don't know the exact details of the value we're interested in?

What if we can only remember the first name of the author, of the book we want?

So we can use wildcards (regex) - which appears totally different from most other languages, which is probalby why it's called wildcard, instead of regex - in fact it probably is different.

```{sql}

SELECT firstname, title FROM BookTable WHERE firstname LIKE 'R%';

-- or something to that effect

```

So there are SQL tricks which simplify the code. That's pretty cool.

So instead of:

```{sql}

select title, pages from book
  where pages >=290 and pages <= 300;

```

We can do:

```{sql}

SELECT title, pages FROM Book
  WHERE pages BETWEEN 290 AND 300;

```

Which countries are the authors from?

So we could do:

```{sql}

SELECT firstname, lastname, country FROM Author
  WHERE country='AU' OR country='BR';

```

But this can quickly become laborious if we want to list several countries.

So we can use the 'IN' operator like so:

```{sql}

SELECT firstname, lastname, country FROM Author
  WHERE country IN ('AU','BR');

```

Which is still going to be pretty laborious if you ask me.

### Sorting: SORT BY ###

Add order by to the select statement

```{sql}

SELECT title FROM book
  ORDER BY title;

```

```{sql}

SELECT title FROM book
  ORDER BY title DESC; -- in descending order

```

```{sql}

SELECT title FROM book
  ORDER BY 2; -- order by column two

```

### Grouping ###

sorting and grouping how the results display

- how to eliminate duplicates
  - and further reduce results

```{sql}

SELECT country FROM Author
  ORDER BY 1;

```

This lists all countries, from all authors. However, when two authors come foerm the same country you will get duplicates. We only really need to know which countries the authors come from, so we can simplify:

```{sql}

SELECT distinct(country) FROM Author;

```

This removes duplicates

OK, now we're getting a little bit more technical. What about when we want to know how many authors come from each country (which from what I remember in R, is not actually that simple - it requires at least the use of pipes in tidyr, or one of Hadley's other wizarding packages.

```{sql}

SELECT country, count(country) 
  FROM Author GROUP BY country;

```

Also, very readable syntax right? Almost as if it was designed for database administrators who aren't sofware developers!

We can also further restrict rows:

We check if there are more than, say, 4 authors in a given country.

The `HAVING` clause works *only* with the `GROUP BY` clause!

```{sql}

SELECT country, count(country) AS COUNT 
  FROM Author 
  GROUP BY country
  HAVING count(country) > 4;

```

OK sweet, this lab looks really helpful. Learn how to create multiple table simultaneously, pull results and group sets.

Also loading data into tables from csv files!! (awesome).

NOTE: Can I pause the course after this lab, and update some notes in the music databse
  - come up with a plan to start consolidating music into tables - create multiple tables at the same time, and pulling out metadata into csv files?
  - still think it would cool to write some python that pulled the metadata and inserted it into my SQL tables

OK, looks like there will be a lot o hand holding in this prac - pre written create tables etc.

But will be cool to see how to load data into the tables
  - this means that if I can get my Music info into a csv file, I can create my tables that way, which would be a fast easy way to do it?

OK, so I learned the point and click way of loading data into a table on the IBM Db2 database server.

Obviously there's a process for doing the same thing on the command line, on my own database here.

    Department.csv
    Employees.csv
    Job_History.csv
    Jobs.csv
    Location.csv

Module 4
--------

### Built-in database functions ###

Allow you to perform operations on the data from within the database - reducing download and bandwith requirements, and making the process more efficient.

You can also write your own database functions - but that's for later.

OK, so we've already used `count()` which is a built-in function

So is `avg()`

```{sql}
SUM()
AVG()
ROUND()
-- WE CAN ALSO PERFORM OPERATIONS, AND APPLY A FUNCTION TO THE OUTPUT
AVG(COST/QUANTITY)
-- THERE ARE ALSO STRING FUNCTIONS THAT OPERATE ON STRINGS
LENGTH() -- COUNTS THE NUMBER OF CHARACTERS IN EACH ELEMENT AND RETURNS THE VALUE
UCASE()
LCASE()
-- can also nest functions within functions
ROUND(AVG())

```

### Date and Time builtins ###

Lost of interesting date and time functions.

```{sql}

DATE()
TIME()
TIMESTAMP()

YEAR()
MONTH()
DAY()
DAYOFMONTH()
DAYOFYEAR()
WEEK()
HOUR()
MINUTE()
SECOND()

```

```{sql}

SELECT COUNT(*) FROM PETRESCUE
  WHERE MONTH(RESCUEDATE) = '05'

SELECT (RESCUEDATE + 3 DAYS) FROM PETRESCUE

```

```{sql}
CURRENT_DATE
CURRENT_TIME
```












