SELECT E.F_NAME, E.L_NAME, D.DEP_NAME 
	FROM EMPLOYEES AS E, DEPARTMENTS AS D
	WHERE DEP_ID = DEPT_ID_DEP
	ORDER BY D.DEP_NAME, E.L_NAME DESC;
	-- SO I GOT THIS FROM THE SOLUTIONS PAGE 
	-- I MISSED THE DEP_ID = DEPT_ID_DEP