SELECT E.F_NAME, E.L_NAME, D.DEP_NAME 
	FROM EMPLOYEES AS E, DEPARTMENTS AS D
	WHERE DEP_ID = DEPT_ID_DEP
	ORDER BY D.DEP_NAME, E.L_NAME DESC;
	-- THIS SEEMS WRONG, UNLESS EVERY EMPLOYEE WORKS IN BOTH DEPARTMENTS